export type FinanceNotification = { id: string; tone: 'info' | 'warning' | 'success'; title: string; titleEs: string; detail: string; detailEs: string; target: 'payments' | 'credit' | 'accounts' };

export function buildFinanceNotifications(input: { fundingNeeded: number; creditUtilization: number; nextDueDays: number | null; potentialSavings: number }): FinanceNotification[] {
  const items: FinanceNotification[] = [];
  if (input.fundingNeeded > 0) items.push({ id: 'funding', tone: 'warning', title: 'Payments need funding', titleEs: 'Falta dinero para próximos pagos', detail: `$${input.fundingNeeded.toFixed(2)} is still needed for scheduled commitments.`, detailEs: `Aún necesitas $${input.fundingNeeded.toFixed(2)} para cubrir tus compromisos programados.`, target: 'payments' });
  else items.push({ id: 'covered', tone: 'success', title: 'Commitments are covered', titleEs: 'Tus compromisos están cubiertos', detail: 'Your available money can cover the current plan.', detailEs: 'Tu dinero disponible cubre el plan actual.', target: 'payments' });
  if (input.creditUtilization > 50) items.push({ id: 'credit', tone: 'warning', title: 'Credit usage is elevated', titleEs: 'El uso de crédito es elevado', detail: `${Math.round(input.creditUtilization)}% of your total limit is currently used.`, detailEs: `Estás utilizando el ${Math.round(input.creditUtilization)}% de tu cupo total. Procura bajarlo de 30%.`, target: 'credit' });
  if (input.nextDueDays !== null && input.nextDueDays <= 2) items.push({ id: 'due', tone: 'info', title: 'A payment is approaching', titleEs: 'Se acerca un pago', detail: input.nextDueDays <= 0 ? 'A commitment is due today or overdue.' : `Your next commitment is due in ${input.nextDueDays} day${input.nextDueDays === 1 ? '' : 's'}.`, detailEs: input.nextDueDays <= 0 ? 'Tienes un compromiso para hoy o ya vencido.' : `Tu próximo compromiso vence en ${input.nextDueDays} día${input.nextDueDays === 1 ? '' : 's'}.`, target: 'payments' });
  if (input.potentialSavings > 0) items.push({ id: 'savings', tone: 'success', title: 'Savings opportunity', titleEs: 'Oportunidad de ahorro', detail: `You could reserve $${input.potentialSavings.toFixed(2)} after current commitments.`, detailEs: `Podrías reservar $${input.potentialSavings.toFixed(2)} después de cubrir tus compromisos.`, target: 'accounts' });
  return items.slice(0, 4);
}
